add wave -position end  sim:/processor/clk
add wave -position end  sim:/processor/reset
add wave -position end  sim:/processor/pc
add wave -position end  /processor/registerFile/regs
add wave -position end  sim:/processor/in_port
add wave -position end  sim:/processor/out_port
add wave -position end  /processor/memory/memory_arr
add wave -position end  sim:/processor/alu/Z
add wave -position end  sim:/processor/alu/N
add wave -position end  sim:/processor/alu/O
add wave -position end  sim:/processor/alu/C